name: get_starter_kit_2024
version: 0.0.1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.8
  get: ^4.6.6
  get_cli: ^1.9.1
  flutter_screenutil: ^5.9.3
  get_storage: ^2.1.1
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  firebase_messaging: ^15.1.3
  flutter_local_notifications: ^17.2.3
  encrypt: ^5.0.3
  logger: ^2.4.0
  dio: ^5.7.0
  catcher_2: ^2.0.0
  path_provider: ^2.1.4
  pretty_dio_logger: ^1.4.0
  freezed_annotation: ^2.4.4
  google_fonts: ^6.2.1
  pinput: ^4.0.0
  flutter_form_builder: ^9.2.1
  flutter_easyloading: ^3.0.5
  lottie: ^3.1.0
  flutter:
    sdk: flutter

dev_dependencies:
  build_runner: ^2.4.13
  json_serializable: ^6.8.0
  freezed: ^2.5.7
  flutter_test:
    sdk: flutter

dependency_overrides:
  fluttertoast: ^8.2.8
  platform: ^3.1.5
  collection: ^1.19.0

flutter:
  assets:
    - assets/images/
    - assets/lottie/
  uses-material-design: true
