import 'dart:convert';

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:get/get_connect/http/src/response/response.dart';
// required: associates our `main.dart` with the code generated by Freezed
part 'response_model.freezed.dart';
// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'response_model.g.dart';

@freezed
class ResponseModel with _$ResponseModel {
  const factory ResponseModel({
    // required this.success,
    required dynamic data,
    required String message,
    required int responseCode,
    //required Response<dynamic> rawRes,
  }) = _ResponseModel;

  factory ResponseModel.fromJson(Map<String, Object?> json)
  => _$ResponseModelFromJson(json);

}
